sudo: false
language: python
dist: xenial
python:
  - 2.7
  - 3.7
cache:
  pip: true
install:
  - pip install coverage matplotlib scipy
script:
  - nosetests --with-coverage --cover-branches
after_success:
  - bash <(curl -s https://codecov.io/bash)
